import { test as devTest, expect } from '@playwright/test';
import { test as harnessTest } from './pwa-fixtures.js';

/**
 * Public offline entry / install-metadata coverage.
 *
 * This spec runs in two places:
 * - the owned production HTTPS harness (`playwright.pwa.config.ts`), where the
 *   self-signed origin is reachable only through the SPKI-pinned persistent
 *   context in `./pwa-fixtures`; and
 * - the plain dev-server suite (`playwright.config.ts`), where the default
 *   Playwright browser is correct.
 *
 * Selecting the fixture by harness env keeps both honest: the harness gets the
 * trusted context, and the dev run keeps its real (non-worker) behavior. `/sw.js`
 * is generated by the postbuild step, so the dev run tolerates 404 rather than
 * asserting production worker headers that only exist in the packaged build;
 * those headers/behavior are asserted in `pwa-worker.spec.ts`.
 */
const harnessConfigured = Boolean(process.env.PWA_BROWSER_PROFILE && process.env.PWA_TLS_SPKI);
const harnessOrigin = 'https://localhost:3443';
const test = harnessConfigured ? harnessTest : devTest;

test.beforeEach(({ baseURL }, testInfo) => {
  // The PWA config points at the owned HTTPS harness. Without its SPKI trust the
  // default browser cannot reach that origin, so skip instead of erroring.
  if (baseURL === harnessOrigin && !harnessConfigured) {
    testInfo.skip(true, 'Owned PWA HTTPS harness trust is not configured');
  }
});

test('public offline entry serves install metadata without authenticated content', async ({ page }) => {
  const response = await page.goto('/offline');

  expect(response?.ok()).toBe(true);
  expect(response?.headers()['content-security-policy']).toContain("worker-src 'self'");
  await expect(page.getByRole('heading', { name: 'A little room to read offline' })).toBeVisible();
  await expect(page.getByRole('status')).toBeVisible();
  await expect(page.getByText(/sign in while online to save reading for offline use/i)).toBeVisible();

  const metadata = await page.evaluate(async () => {
    const manifestResponse = await fetch('/manifest.webmanifest');
    const manifest = await manifestResponse.json();
    return {
      manifestStatus: manifestResponse.status,
      name: manifest.name,
      startUrl: manifest.start_url,
      scope: manifest.scope,
      display: manifest.display,
      icons: manifest.icons,
      appleIcon: document.querySelector('link[rel="apple-touch-icon"]')?.getAttribute('href'),
      bodyText: document.body.innerText,
    };
  });

  expect(metadata.manifestStatus).toBe(200);
  expect(metadata.name).toBe('Transform Lit');
  expect(metadata.startUrl).toBe('/offline');
  expect(metadata.scope).toBe('/');
  expect(metadata.display).toBe('standalone');
  expect(metadata.icons).toEqual(expect.arrayContaining([
    expect.objectContaining({ src: '/icons/pwa-192.png', sizes: '192x192' }),
    expect.objectContaining({ src: '/icons/pwa-512.png', sizes: '512x512' }),
    expect.objectContaining({ src: '/icons/pwa-maskable-512.png', sizes: '512x512', purpose: 'maskable' }),
  ]));
  expect(metadata.appleIcon).toBe('/icons/apple-touch-icon.png');
  expect(metadata.bodyText).not.toMatch(/saved for you|hello,|your bookshelf/i);

  const serviceWorkerStatus = await page.evaluate(async () => (await fetch('/sw.js')).status);
  // The packaged build serves the generated worker (200); the dev server returns
  // 404. Assert the honest set instead of inventing a production-only value.
  expect([200, 404]).toContain(serviceWorkerStatus);
});

test('install guidance remains available when native install prompting is not offered', async ({ page }) => {
  await page.goto('/offline');
  await expect(page.getByText(/use your browser menu to add this page to your home screen/i)).toBeVisible();
});
