export default {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: { '^.+\\.(t|j)s$': 'ts-jest' },
  collectCoverageFrom: [
    '**/*.ts',
    '!**/*.module.ts',
    '!**/*.model.ts',
    '!**/models/**',
    '!**/main.ts',
    '!**/azure/**',
    '!**/chat/pubsub.service.ts',
    '!**/auth/strategies/google.strategy.ts',
    '!**/generate-schema.ts',
    '!**/common/decorators/**',
    '!**/prisma/prisma.service.ts',
    '!**/auth/auth.controller.ts',
    '!**/index.ts',
  ],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  passWithNoTests: true,
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
    '^(\\.{1,2}/.*)\\.js$': '$1',
    '^@transformlit/shared$': '<rootDir>/../../../packages/shared/src/index.ts',
  },
  coverageThreshold: {
    global: {
      lines: 70,
      branches: 60,
      functions: 70,
      statements: 70,
    },
  },
};
